#!/usr/bin/env python3
"""Create the unified single-cell notebook"""

import json

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🎨 SD-DarkMaster-Pro Unified Interface\n",
                "\n",
                "This is a single-cell notebook that launches a comprehensive Streamlit interface for managing all SD WebUI operations.\n",
                "\n",
                "**Features:**\n",
                "- ✅ One-click setup and configuration\n",
                "- 📦 Model browsing and selection (SD1.5, SDXL, CivitAI)\n",
                "- 💾 Download management with progress tracking\n",
                "- 🚀 WebUI launcher with multiple options\n",
                "- 🧹 Storage management and cleanup\n",
                "- 📊 Real-time monitoring and logs\n",
                "\n",
                "Simply run the cell below to access the complete interface!"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {
                "cellView": "form",
                "id": "unified_interface"
            },
            "outputs": [],
            "source": [
                "#@title 🚀 Launch SD-DarkMaster-Pro Unified Interface\n",
                "#@markdown This single cell handles everything - setup, downloads, and WebUI launch!\n",
                "\n",
                "import os\n",
                "import sys\n",
                "import subprocess\n",
                "import time\n",
                "from pathlib import Path\n",
                "\n",
                "# Configuration\n",
                "ngrok_token = \"\" #@param {type:\"string\"}\n",
                "tunnel_choice = \"cloudflared\" #@param [\"cloudflared\", \"ngrok\", \"localtunnel\", \"none\"]\n",
                "auto_launch = True #@param {type:\"boolean\"}\n",
                "\n",
                "print(\"🎨 SD-DarkMaster-Pro Unified Interface\")\n",
                "print(\"=\" * 50)\n",
                "\n",
                "# Detect platform\n",
                "if os.path.exists('/content'):\n",
                "    platform = 'colab'\n",
                "    base_path = Path('/content')\n",
                "elif os.path.exists('/kaggle'):\n",
                "    platform = 'kaggle'\n",
                "    base_path = Path('/kaggle/working')\n",
                "else:\n",
                "    platform = 'local'\n",
                "    base_path = Path.home()\n",
                "\n",
                "print(f\"🖥️  Platform: {platform}\")\n",
                "project_path = base_path / 'SD-DarkMaster-Pro'\n",
                "\n",
                "# Clone repository if needed\n",
                "if not project_path.exists():\n",
                "    print(\"\\n📥 Cloning repository...\")\n",
                "    !git clone https://github.com/remphanostar/SD-DarkMaster-Pro.git {project_path}\n",
                "else:\n",
                "    print(\"\\n📂 Repository already exists\")\n",
                "    os.chdir(project_path)\n",
                "    !git pull\n",
                "\n",
                "# Install requirements\n",
                "print(\"\\n📦 Installing requirements...\")\n",
                "requirements = ['streamlit', 'pyngrok', 'psutil', 'requests', 'beautifulsoup4']\n",
                "for req in requirements:\n",
                "    subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', req])\n",
                "\n",
                "# Install cloudflared if needed\n",
                "if tunnel_choice == 'cloudflared' and not os.path.exists('/usr/local/bin/cloudflared'):\n",
                "    print(\"\\n📥 Installing Cloudflare Tunnel...\")\n",
                "    !wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O cloudflared\n",
                "    !chmod +x cloudflared\n",
                "    !sudo mv cloudflared /usr/local/bin/\n",
                "\n",
                "# Set ngrok token\n",
                "if ngrok_token:\n",
                "    os.environ['NGROK_AUTH_TOKEN'] = ngrok_token\n",
                "\n",
                "# Launch Streamlit app\n",
                "print(\"\\n🚀 Launching unified interface...\")\n",
                "print(\"-\" * 50)\n",
                "\n",
                "# Kill any existing Streamlit processes\n",
                "subprocess.run(['pkill', '-f', 'streamlit'], capture_output=True)\n",
                "time.sleep(2)\n",
                "\n",
                "# Start Streamlit in background\n",
                "app_path = project_path / 'scripts' / 'unified_app.py'\n",
                "process = subprocess.Popen([\n",
                "    sys.executable, '-m', 'streamlit', 'run',\n",
                "    str(app_path),\n",
                "    '--server.port', '8501',\n",
                "    '--server.headless', 'true',\n",
                "    '--logger.level', 'error'\n",
                "], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)\n",
                "\n",
                "# Wait for server to start\n",
                "print(\"⏳ Starting Streamlit server...\")\n",
                "time.sleep(5)\n",
                "\n",
                "# Create tunnel based on choice\n",
                "public_url = None\n",
                "\n",
                "if tunnel_choice == \"cloudflared\":\n",
                "    print(\"\\n🌐 Creating Cloudflare Tunnel...\")\n",
                "    # Start cloudflared in background\n",
                "    cf_process = subprocess.Popen(\n",
                "        ['cloudflared', 'tunnel', '--url', 'http://localhost:8501'],\n",
                "        stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True\n",
                "    )\n",
                "    \n",
                "    # Wait for URL\n",
                "    for i in range(30):\n",
                "        line = cf_process.stderr.readline()\n",
                "        if 'trycloudflare.com' in line:\n",
                "            public_url = line.split('https://')[1].split(' ')[0]\n",
                "            public_url = f'https://{public_url}'\n",
                "            break\n",
                "        time.sleep(0.5)\n",
                "    \n",
                "elif tunnel_choice == \"ngrok\" and ngrok_token:\n",
                "    try:\n",
                "        from pyngrok import ngrok\n",
                "        # Set auth token\n",
                "        ngrok.set_auth_token(ngrok_token)\n",
                "        # Close any existing tunnels\n",
                "        for tunnel in ngrok.get_tunnels():\n",
                "            ngrok.disconnect(tunnel.public_url)\n",
                "        # Create new tunnel\n",
                "        public_url = ngrok.connect(8501)\n",
                "    except Exception as e:\n",
                "        print(f\"\\n⚠️  Ngrok error: {e}\")\n",
                "        \n",
                "elif tunnel_choice == \"localtunnel\":\n",
                "    print(\"\\n🌐 Creating LocalTunnel...\")\n",
                "    !npm install -g localtunnel 2>/dev/null\n",
                "    lt_process = subprocess.Popen(\n",
                "        ['lt', '--port', '8501'],\n",
                "        stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True\n",
                "    )\n",
                "    # Wait for URL\n",
                "    for i in range(10):\n",
                "        line = lt_process.stdout.readline()\n",
                "        if 'your url is:' in line.lower():\n",
                "            public_url = line.split('is:')[1].strip()\n",
                "            break\n",
                "        time.sleep(0.5)\n",
                "\n",
                "# Display access information\n",
                "if public_url:\n",
                "    print(f\"\\n✅ Interface is ready!\")\n",
                "    print(f\"\\n🌐 Access your dashboard at: {public_url}\")\n",
                "    print(f\"\\n📱 Share this link to access from any device\")\n",
                "else:\n",
                "    print(f\"\\n✅ Interface is running locally!\")\n",
                "    print(f\"\\n💡 Access at: http://localhost:8501\")\n",
                "    if platform == 'colab':\n",
                "        print(f\"\\n⚠️  For Colab, you need a tunnel. Try setting tunnel_choice to 'cloudflared'\")\n",
                "\n",
                "print(\"-\" * 50)\n",
                "\n",
                "# Display instructions\n",
                "print(\"\\n📖 Quick Start Guide:\")\n",
                "print(\"1. Click the link above to open the interface\")\n",
                "print(\"2. Navigate to 'Setup' to configure your environment\")\n",
                "print(\"3. Go to 'Models' to select what to download\")\n",
                "print(\"4. Use 'Downloads' to manage your download queue\")\n",
                "print(\"5. Launch your preferred WebUI from 'Launch'\")\n",
                "print(\"6. Monitor everything from the 'Home' dashboard\")\n",
                "\n",
                "# Keep the cell running\n",
                "print(\"\\n✨ Interface is running. This cell will stay active.\")\n",
                "print(\"⚠️  Don't close this cell or the interface will stop!\")\n",
                "\n",
                "# Optional: Auto-open the URL\n",
                "if auto_launch and 'public_url' in locals():\n",
                "    try:\n",
                "        from IPython.display import Javascript\n",
                "        display(Javascript(f'window.open(\\\"{public_url}\\\", \\\"_blank\\\");'))\n",
                "    except:\n",
                "        pass\n",
                "\n",
                "# Keep process alive\n",
                "try:\n",
                "    while True:\n",
                "        time.sleep(1)\n",
                "        if process.poll() is not None:\n",
                "            print(\"\\n❌ Streamlit process ended unexpectedly\")\n",
                "            break\n",
                "except KeyboardInterrupt:\n",
                "    print(\"\\n👋 Shutting down...\")\n",
                "    process.terminate()"
            ]
        }
    ],
    "metadata": {
        "colab": {
            "provenance": [],
            "gpuType": "T4"
        },
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10.0"
        },
        "accelerator": "GPU"
    },
    "nbformat": 4,
    "nbformat_minor": 0
}

# Write notebook
with open('/workspace/notebook/SD-DarkMaster-Pro-Unified.ipynb', 'w') as f:
    json.dump(notebook, f, indent=2)

print("✅ Created SD-DarkMaster-Pro-Unified.ipynb")